### ISSUE TITLE
cannot install requirements

### ISSUE THREAD

**Issue by dongjinkimif** [zsaladin/show-me-my-salary#3]
when trying to install modules in requirements.txt, I cannot proceed with the following message.
======================================================================
>source venv/bin/activate
(venv)>pip install requirements.txt                                                                      
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by zsaladin** [comment]
Thank you for your feedback.
In my opinion you should modify your command for installing requirements.

Your command:
pip install requirements.txt

Correct command:
pip install -r requirements.txt

**Comment by dongjinkimif** [comment]
it works! thank you
